project_name: terraform-lsp
before:
  hooks:
    - go mod download
release:
  github:
    owner: juliosueiras
    name: terraform-lsp
  name_template: '{{.Tag}}'
brew:
  name: terraform-lsp
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  install: bin.install "terraform-lsp"
scoop:
  name: terraform-lsp
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  url_template: https://github.com/juliosueiras/terraform-lsp/releases/download/{{
    .Tag }}/{{ .ArtifactName }}
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  targets:
  - linux_amd64
  - darwin_amd64
  - windows_amd64
  main: .
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: terraform-lsp
  lang: go
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  download: https://github.com
