language: nix
jobs:
  include:
    - language: nix
      os: linux
      env: TRAVIS_OS=linux
    - language: nix
      os: osx
      env: TRAVIS_OS=osx
    - stage: GitHub Release
      language: go
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true


after_script:
  - file ./result/bin/terraform-lsp
