jobs:
  include:
    - script: echo "Testing"
    #  - language: nix
    #    os: linux
    #    env: TRAVIS_OS=linux
    #  - language: nix
    #    os: osx
    #    env: TRAVIS_OS=osx
    - stage: GoReleaser Deployment
      services:
        - docker
      language: go
      deploy:
        - provider: script
          skip_cleanup: true
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux

after_script:
  - file ./result/bin/terraform-lsp
