[[constraint]]
  name = "github.com/creachadair/jrpc2"
  version = "0.1.2"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/hcl2"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.12.0"

[[constraint]]
  branch = "master"
  name = "github.com/sourcegraph/go-lsp"

[[constraint]]
  branch = "master"
  name = "github.com/zclconf/go-cty"

[prune]
  go-tests = true
  unused-packages = true
